FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build

WORKDIR /src

COPY ["BlazorZeus/BlazorZeus.csproj", "BlazorZeus/"]
COPY ["ZeusCore/ZeusCore.csproj", "ZeusCore/"]

RUN dotnet restore "BlazorZeus/BlazorZeus.csproj"

COPY . .
WORKDIR "/src/BlazorZeus"
#RUN dotnet build "BlazorZeus.csproj" -c Release -o /app/build

# FROM build AS publish
RUN dotnet publish "BlazorZeus.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim

WORKDIR /app

RUN mkdir -p movies
RUN mkdir -p series
RUN mkdir -p save
RUN mkdir -p config
RUN mkdir -p Database
RUN mkdir -p Logs

COPY --from=build /app/publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "BlazorZeus.dll"]